import 'package:iconfont/models/index.dart';
import 'package:iconfont/src/utils.dart';

/// IconTemp
class IconTemp {
  /// build
  static String build(String className, IconModel model) {
    var itemContent = model.glyphs
        ?.map((e) =>
            _buildItem(model.cssPrefixText ?? "", e, model.package != null))
        .join("\n");

    String contents = '''
//  This file is automatically generated. DO NOT EDIT, all your changes would be lost.
//  https://pub.dartlang.org/packages/iconfont

import 'package:flutter/material.dart' show IconData;

class $className {
  static const String _family = '${model.fontFamily}';
  static const String? _package = '${model.package}';
  
  $className._();
  
$itemContent
}
''';

    return contents;
  }

  /// _buildItem
  static String _buildItem(
      String preText, IconModelGlyphs glyphs, bool withPackage) {
    String iconName = Utils.formatName("${preText}${glyphs.fontClass}");
    String unicode = glyphs.unicode ?? "";
    String glyphsName = "";
    String packageName = "";
    if (glyphs.name != null && glyphs.name!.isNotEmpty) {
      glyphsName = "// ${glyphs.name}";
    }
    if (withPackage) {
      packageName = ", fontPackage: _package";
    }

    return '''  static const IconData $iconName = IconData(0x$unicode, fontFamily: _family$packageName); $glyphsName''';
  }
}
